platform: linux

image_resource:
  type: docker-image
  source:
    repository: kciepluc/pwgen-docker

inputs:
  - name: workshop
outputs:
  - name: terraform-files

run:
  path: ./workshop/ci/tasks/passwords/task.sh