groups:
- name: Packer
  jobs:
  - packer-azure


resources:
- name: workshop
  type: git
  source:
    uri: https://github.com/warroyo/win-container-workshop

jobs:
- name: packer-azure
  plan:
  - get: workshop
  - task: packer
    file: workshop/ci/tasks/packer/task.yml
    params:
      ARM_CLIENT_ID: ((arm_client_id))
      ARM_CLIENT_SECRET: ((arm_client_secret))
      ARM_TENANT_ID: ((arm_tenant_id))
      ARM_SUBSCRIPTION_ID: ((arm_subscription_id))